### ISSUE TITLE
Bulkrax: Round Trip Generated Metadata

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#218]
'- intention is for tenant data transfer into a new instance of hyku that is based off of their own pals
- This ticket will be worked on in a future phase

# Summary
ref #442 comment: https://gitlab.com/notch8/palni-palci/-/issues/442#note_923258865
- [ ] ~~This will likely be an epic of work **for a phase in the future**. We are trading this ticket for exporting collection and fileset bagit (#447 #478) per client mtg 6/13/22. Consider breaking this into several tickets~~
 
- [ ] This was created as a separate ticket because we will need to handle re-importing/re-creating referenced objects. We will also may need to handle exporting them differently as well.
- [ ] for example, we cannot simply export 'embargo_id' to be reimported. Instead, we need to also export the details of that embargo so that in the case we ever need to reinstate the data (and the original exported id no longer exists), we have all of its details as well to be re-created and re-referenced. The id may change. 
- [ ] To not conflict with existing ids, maybe this should be limited to fresh dbs if the intention is to transfer tenant data.
- [ ] attrs to consider: "import_url", "access_control_id", "admin_set_id", "embargo_id", "lease_id".
- [ ] "rendering_ids", "thumbnail_id", and "representative_ids" may be handled in #489
- [ ] Additionally we will need to make the system honor any generated metadata fields we give it. It should not override with the system's auto generated values. ie. dates 

# Acceptance Criteria

On Bulkrax Export, when generated metadata is selected...
- [ ] CSV: a user should be able to re-import the downloaded zip and/or csv that include the generated metadata and/or thumbnail options
- [ ] Bagit: a user should be able to re-import the downloaded zip and/or bag that include the generated metadata and/or thumbnail options
- [ ] "representative_id", "thumbnail_id", "rendering_ids",  may be handled in #489 

# Testing Instructions
- a user should be able to round trip exported downloads, when generated metadata is selected on export.

## Dev Notes: 

HEADS UP: https://github.com/samvera-labs/bulkrax/blob/5db7e5f1d953c352e43554fe76b66a7042ccabd4/lib/bulkrax.rb#L102

**Comment by DiemBTran** [comment]
Related MRs:

- [459-1-add-hint-text-to-export-enhancements](https://gitlab.com/notch8/palni-palci/-/merge_requests/470)
!470
- [i442 export generated metadata rework](https://gitlab.com/notch8/palni-palci/-/merge_requests/471)
!471
- [i442 export generated metadata rework](https://gitlab.com/notch8/palni-palci/-/merge_requests/472)
!472
