### ISSUE TITLE
Contribute the Groups w/ Roles feature to Hyku

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#353]
## Summary

Copy all code related to the Groups with Roles feature from [palni-palci](https://github.com/scientist-softserv/palni-palci) to [Hyku](https://github.com/samvera/hyku). This includes making sure that the code is in a state that can be merged into Hyku. 

Hyku PR: https://github.com/samvera/hyku/pull/1859 

## Subtasks 

- [x] Copy code over 
- [x] #354 
- [x] #355 
- [x] #369
- [x] [GwR] Ensure members of Registered group get included in User.registered scope
  - [This PR review comment](https://github.com/samvera/hyku/pull/1859#discussion_r1068985535)
- [x] #395
- [x] #399
- [ ] ~~#393~~ 
- [ ] ~~#394~~ 
- [x] #396
- [x] #397
- [x] [GwR] Figure out if a solr migration is necessary for a solr schema change
- [x] #400
- [x] Merge code into Hyku 
- [x] #398
- [ ] ~~#382~~ (will track on <-- this ticket)
