### ISSUE TITLE
[GwR] Resolve Rubocop issues without using todo file

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#396]
## Summary

Ref [this comment](https://github.com/samvera/hyku/pull/1859#discussion_r1068963473). 

In the Groups with Roles PR, the rubocop TODO file should not be changed. All newly added TODO's should either be resolved or ignored using code comments denoting that they are intended. 

## Acceptance Criteria 

- [x] Submit a PR against the `groups-with-roles-feature` branch 
- [x] The `.rubocop_todo.yml` file changes have been reverted 
- [x] Rubocop is green

**Comment by bkiahstroud** [comment]
PR: https://github.com/samvera/hyku/pull/1899
