### ISSUE TITLE
Epic: Outgoing OAI should include all public fields

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#403]
# Summary

As a tenant manager, I want to be able to allow for harvesting of my tenant through OAI.  Currently the OAI feed is not complete and is missing many metadata fields.  Allow for all public metadata fields to be included in the OAI feed, as well as a link to the file/files associated. 

# Acceptance Criteria

- [ ] All public metadata fields are available on records for tenants in hyku
- [ ] links to public files on works are available.  
- [ ] Documentation on how to access an OAI feed is present. (What URL does a user need, what is the metadata prefix, what is the identifier used in Pals?). 
- [ ] Contribute back to hyku if possible.  

This work will be completed on issues: 
#421 
#422 
#423 
#424 
#425 

# Testing Instruction

1. select a tenant and use the documentation provided above and this playbook article to access the OAI feed.
2. Select a record from the tenant and look it up in the OAI feed.  
3. Confirm all public metadata is available
4. confirm all public files are available by URL in the feed. 

# Notes

Jio and Adventist are utilizing adaptions to the OAI outgoing gem that allows for all metadata fields instead of just Dublin Core Metadata.  Rob, Jeremy, or Braydon may have additional insight. 

Standard format for oai url in hyku is: https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

**Comment by crisr15** [comment]
Ticket was pointed between and 8 and a 13.  Discuss in sprint planning.

**Comment by crisr15** [comment]
Break into 2 tickets: 
Add ticket for:  do the  weirdest field in bunch.  
Spit each acceptance criteria into tickets.

**Comment by crisr15** [comment]
Closing as all associated tickets are closed.
