### ISSUE TITLE
Analytics - Collection Report shows deleted collections

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#408]
# Summary
references issue https://github.com/scientist-softserv/palni-palci/issues/391

When I look at the Collections Report for individual tenants, many (not all) of them share identical lists of "Collection deleted" collections with identical numbers, including brand new tenants that have never had collections created. Is this data that will be gradually replaced with accurate per-tenant data as views start to roll in with the analytics enabled, or is it something worry about? (The works, on the other hand, simply show no files, which is what I would have expected for collections as well.)

# Acceptance Criteria

- [ ] When a tenant has no collections, the collections report will not display any collections.
- [ ] When a tenant has collections, you do not see 'collection deleted' collections.  

# Screenshots or Video
![Screenshot 2023-04-24 at 12 10 13 PM](https://user-images.githubusercontent.com/11359350/234093039-7162f17e-ac44-4d5a-85d6-0cb1593dabd9.png)

# Testing Instructions

- [ ] Go to a tenant that has Deleted collections, and go to the collection report under analytics (screenshot from commons archive Notch8 tenant). 
- [ ] Confirm you can not see Deleted collections.  
- [ ] Find a tenant without collections, Go to collection report under analytics and confirm you can not see any deleted collections.  

# Notes
In Hyrax `app/controllers/hyrax/admin/analytics/collection_reports_controller.rb`
this is a rescue from the collections being nil. May need to put a nil check here

**Comment by aprilrieger** [comment]
https://dev.commons-archive.org/admin/analytics/collection_reports?locale=en

**Comment by aprilrieger** [comment]
@labradford for the acceptance criteria of: When a tenant has no collections, the collections report will not display any collections.
- Find a tenant without collections, Go to collection report under analytics and confirm you can not see any deleted collections.

What should this read: Find a tenant without collections, Go to collection report under analytics and confirm you can not see the --->Top collection partial?

**Comment by labradford** [comment]
Find a tenant without collections, Go to collection report under analytics and confirm you can not see any collections, deleted or otherwise

**Comment by aprilrieger** [comment]
desired behavior when a collection has no collections to show:: show the partial but no collections present. slack convo link: https://assaydepot.slack.com/archives/C03B6A93E31/p1683247704451829

**Comment by alishaevn** [comment]
this work will be implemented in 3 phases. overall, we've moved analytics to a per tenant system instead of per application. this does mean that deleted collections will show in a tenant, for historical purposes. however, by the end of phase 3 if you see a deleted collection it is because it was deleted under that tenant's analytics account, not because it's trying to pull data from another tenant. which is currently the case.

## phase one
add analytics settings fields on the tenant level: dashboard >> settings >> account >> (look for fields that begin with "analytics"). these fields need to be filled out for **each** tenant where analytics are desired, with their own account info so that analytics are specific to that tenant. refer to [these instructions](https://github.com/scientist-softserv/palni-palci#analytics-feature) on how to get/create these values.

in order to not lose any tracking time, tenants without the above settings will continue using the account that is currently set app wide as a fallback.

## phase two
once you've had a chance to update the chosen tenants on the demo environment, we will remove the fallback system for the demo environment. any tenants without analytics settings at the tenant level, will no longer have analytic tracking set up. any analytics partials (like the user graph on the dashboard, etc.) will no longer show for them. the tenants with analytics settings will continue as is.

upon your client qa approval, we will also push the phase one code changes to production so that those tenants can be updated.

## phase three
once you've had a chance to update the chosen tenants on the production environment, we will remove the fallback system for the production environment. any tenants without analytics settings at the tenant level, will no longer have analytic tracking set up. any analytics partials (like the user graph on the dashboard, etc.) will no longer show for them. the tenants with analytics settings will continue as is.

**Comment by alishaevn** [comment]
this work (along with #409) will be implemented in 3 phases. overall, we've moved analytics to a per tenant system instead of per application. this does mean that deleted collections will show in a tenant, for historical purposes. however, by the end of phase 3 if you see a deleted collection it is because it was deleted under that tenant's analytics account, not because it's trying to pull data from another tenant. which is currently the case.

## phase one
add analytics settings fields on the tenant level: dashboard >> settings >> account >> (look for fields that begin with "analytics"). these fields need to be filled out for **each** tenant where analytics are desired, with their own account info so that analytics are specific to that tenant. refer to [these instructions](https://github.com/scientist-softserv/palni-palci#analytics-feature) on how to get/create these values.

in order to not lose any tracking time, tenants without the above settings will continue using the account that is currently set app wide as a fallback.

## phase two
once you've had a chance to update the chosen tenants on the demo environment, we will remove the fallback system for the demo environment. any tenants without analytics settings at the tenant level, will no longer have analytic tracking set up. any analytics partials (like the user graph on the dashboard, etc.) will no longer show for them. the tenants with analytics settings will continue as is.

upon your client qa approval, we will also push the phase one code changes to production so that those tenants can be updated.

## phase three
once you've had a chance to update the chosen tenants on the production environment, we will remove the fallback system for the production environment. any tenants without analytics settings at the tenant level, will no longer have analytic tracking set up. any analytics partials (like the user graph on the dashboard, etc.) will no longer show for them. the tenants with analytics settings will continue as is.

**Comment by alishaevn** [comment]
## phase 1 softserv qa
settings were applied to the dev.commons-archive.org tenant on demo.
![Screenshot 2023-05-19 at 10 49 08 AM](https://github.com/scientist-softserv/palni-palci/assets/29032869/69c2c440-6e34-4905-9d6d-6c2b08caaa5a)

**Comment by alishaevn** [comment]
phase 2 has been deployed to the demo environment.

at this point, only the "dev" tenant has any analytics set up because I saved them as mentioned in the instructions for phase 1. (unless someone else saved the analytics info for other tenants).
you can compare https://dev.commons-archive.org/admin/analytics/collection_reports?locale=en to https://butler.commons-archive.org/admin/analytics/collection_reports?locale=en, for example.

we're moving the "phase 3" steps into its own ticket. per today's [client meeting](https://docs.google.com/document/d/1ASOWLZhFBeMUw1KTWxAmEdotbvM471RgQfe2BhkQJ_Q/edit), pals will hold off on having the production tenants set up their own analytics accounts until the google analytics 4 switch is ready to happen. that way both things can happen at once.

ref:
- #569

**Comment by alishaevn** [comment]
closing this issue since nic moved it to "done" on the pals board yesterday.
