### ISSUE TITLE
Epic: Theming

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#462]
# Story

Design and theming work will be applied to two situations:
- Work and search pages will be themed. The rest of the Hyku pages will be hidden from access.
- Universal Viewer will get themed, with configurations modifiable by an operator.

# Acceptance Criteria

- [ ] There is a ReShare show page theme
- [ ] ReShare show page theme only has UV and Metadata
- [ ] ReShare show page theme will have links back to ReShare for additional search
- [ ] There is no link to the Hyku search results page

# Testing Instructions and Sample Files

-

# Notes

Do pages need to be hidden, or do we just hide the links to get from the work page to other pages.  
What should the theming look like?  (Can we get a branding guide or some outline of desired changes)
What changes do we need to make to the UV? 
Do we still want to theme the search page, or is discovery happening in the ReShare app? 

## Theming
Design and theming work will be applied to two situations:
- Work and search pages will be themed. The rest of the Hyku pages will be hidden from access.
- Universal Viewer will get themed, with configurations modifiable by an operator.
