### ISSUE TITLE
EPIC - Set up SSO on per tenant basis

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#472]
# Story
part of #463 

As a tenant admin, I can add SSO information so I can enable SSO for my tenant

# Acceptance Criteria

- [ ] As an admin, I can configure SSO in a tenant
- [ ] As an admin, I can enter SSO configurations - either SAML or OIDC
- [ ] A dynamic form will load the appropriate fields for basic SAML or OIDC configurations

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

- Login as an admin
- Visit tab on dashboard for entering SSO Configuration
- Enter SSO configuration options for SAML 
- Verify SSO is enabled and users can login to a SAML configured provider
- Enter SSO configuration options for OIDC 
- Verify SSO is enabled and users can login to a OIDC configured provider

# Notes
Related to #471 

# Implementation

Create Account level omniauth config objects
Provide omniauth config base on tenant selected
LOOK AT DOT `config/initializers/devise.rb` for an example
See code snippet generated by ChatGPT in #463 for a starting point

Load tenant in Application controller, change the omniauth config

**Comment by labradford** [comment]
- create dynamic configuration part - admin tab and model - 3
- feed dynamic credentials into omniauth - 8
