### ISSUE TITLE
Add troubleshooting script button to dashboard

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#844]
## Summary
https://assaydepot.slack.com/archives/C0313NKC08L/p1678912353694389?thread_ts=1678804802.634039&cid=C0313NKC08L

Pals would like to add a few buttons in the UI that would trigger commands that allow tenant admins to run 'data repair' tasks. They would like a paragraph near each button explaining what it does and when you'd need to us it. 

Scripts to include:
- Generate missing Workflow Roles
  - fix problems related to approving works
- Grant groups appropriate access to all records
  - fixes issues related to users not having abilities they should for certain records

## Tasks

- [x] Each of the following `RoleService` methods should be extracted to an `ApplicationJob#perform` method; these jobs should be an inner class within the existing `RoleService` (e.g. `RoleService::CreateAdminSetAccessesJob`).  The existing methods (e.g. `RolesService.grant_workflow_roles_for_all_admin_sets!`) should call `#perform_now` on their corresponding job (this is to preserve existing method interfaces).
  - [x] `RolesService.grant_workflow_roles_for_all_admin_sets!`
  - [x] `RolesService.create_collection_accesses!`
  - [x] `RolesService.create_admin_set_accesses!`
  - [x] `RolesService.create_collection_type_participants!`
- [x] Create a controller end-point for these administrative functions:
  - [x] Authorize the action via `authorize! :update, RoleService`
  - [x] The job name could be a parameter in the URL (e.g. `/admin/role_services/:job_name_key`); thus requiring only one controller action.
  - [x] The action should require a `POST` request.
  - [x] The action should handle HTML and JSON requests; HTML should flash a `notice` of the job submitted.
- [x] Create a view for submitting these jobs
  - [x] Each button/link will need a paragraph of descriptive text.
- [x] Create a link on the Admin menu to show the above view
  - [x] The link should be wrapped by `can :update, RoleService`
- [x] Create an ability entry for `can! :update, RoleService`
  - [x] Question: Is this a new role that we want to expose?  Is it adequate to say that you must be an admin to be able to `:update RoleService`?

Consideration; the rake tasks loop through each tenant and for each tenant call the corresponding `RoleService` method.  Put another way, these administrative actions may need to consider per tenant basis and/or proprietor.

## Acceptance Criteria

- Buttons for the following are included as a new menu option off of the admin menu.
  - [ ] Grant groups appropriate access to all records
  - [ ] Generate missing Workflow Roles
  - [ ] Create collection access records
  - [ ] Create admin set access records
  
## Caveats

Given that there is a request for a "paragraph of text explaining each button"; we want to consider that a drop down menu option might not be ideal.  This might mean a full page for administrative tasks.

## Testing

Navigate to dashboard and select Data Repair menu.
Click button
Verify that appropriate job was submitted to job queue

**Comment by jillpe** [comment]
Can you provide more details on this?

**Comment by ndroark** [comment]
This is something Kiah had suggested in Slack: "It would be possible to add a few buttons in the UI that would trigger these commands, which would make it possible for tenant admins to run these 'data repair' tasks. We’d probably want to add a paragraph near each button explaining what it does and when you’d need to use it, but actually hooking the button up to the code would be very simple."

**Comment by bkiahstroud** [comment]
"Scripts" that I believe would be good candidates for this ticket: 

- [`RolesService.grant_workflow_roles_for_all_admin_sets!`](https://github.com/scientist-softserv/palni-palci/blob/3f7b9741fdae40df617562c1bc9f084b106ac5d3/app/services/roles_service.rb#L224-L234) <-- highest priority, this has been the most common roles-related data repair task needed by far 
- [`RolesService.create_collection_accesses!`](https://github.com/scientist-softserv/palni-palci/blob/3f7b9741fdae40df617562c1bc9f084b106ac5d3/app/services/roles_service.rb#L100-L134)
- [`RolesService.create_admin_set_accesses!`](https://github.com/scientist-softserv/palni-palci/blob/3f7b9741fdae40df617562c1bc9f084b106ac5d3/app/services/roles_service.rb#L136-L169)
- [`RolesService.create_collection_type_participants!`](https://github.com/scientist-softserv/palni-palci/blob/3f7b9741fdae40df617562c1bc9f084b106ac5d3/app/services/roles_service.rb#L171-L193)

I don't think this is relevant for this task, but for visibility, these all have corresponding rake tasks [here](https://github.com/scientist-softserv/palni-palci/blob/main/lib/tasks/roles.rake) (which is why I originally called them "scripts")
