### ISSUE TITLE
☄ EPIC: Contribute back features to HYKU proper

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni-palci#903]
When we work on PALS, its features should get contributed back to HYKU proper - main by default. 

Adventist_dev should be contributed back too

# Acceptance Criteria

- [x] https://github.com/scientist-softserv/palni-palci/issues/904
- [x] https://github.com/scientist-softserv/palni-palci/issues/905
- [x] https://github.com/scientist-softserv/palni-palci/issues/277
- [ ] https://github.com/scientist-softserv/palni-palci/issues/125
- [ ] https://github.com/scientist-softserv/palni-palci/issues/140
- [ ] https://github.com/scientist-softserv/palni-palci/issues/275
- [ ] https://github.com/scientist-softserv/palni-palci/issues/277
- [ ] https://github.com/scientist-softserv/palni-palci/issues/448
- [ ] https://github.com/scientist-softserv/palni-palci/issues/740
- [ ] https://github.com/scientist-softserv/palni-palci/issues/742
- [ ] https://github.com/scientist-softserv/palni-palci/issues/742
- [ ] https://github.com/scientist-softserv/palni-palci/issues/746
- [x] https://github.com/scientist-softserv/palni-palci/issues/748
- [ ] https://github.com/scientist-softserv/palni-palci/issues/772
- [ ] https://github.com/scientist-softserv/palni-palci/issues/773
- [ ] https://github.com/scientist-softserv/palni-palci/issues/774
- [ ] https://github.com/scientist-softserv/palni-palci/issues/776
- [ ] https://github.com/scientist-softserv/palni-palci/issues/778
- [ ] https://github.com/scientist-softserv/palni-palci/issues/839
- [ ] https://github.com/scientist-softserv/palni-palci/issues/840
- [x] https://github.com/scientist-softserv/palni-palci/issues/843
- [x] https://github.com/scientist-softserv/palni-palci/issues/844
- [ ] https://github.com/scientist-softserv/palni-palci/issues/864
- [ ] https://github.com/scientist-softserv/palni-palci/issues/903
- [ ] https://github.com/scientist-softserv/palni-palci/issues/906
- [ ] https://github.com/scientist-softserv/palni-palci/issues/907
- [x] https://github.com/scientist-softserv/palni-palci/issues/911
- [ ] https://github.com/scientist-softserv/palni-palci/issues/913
- [ ] https://github.com/scientist-softserv/palni-palci/issues/914
- [ ] https://github.com/scientist-softserv/palni-palci/issues/915
- [x] https://github.com/scientist-softserv/palni-palci/issues/910
- [ ] https://github.com/scientist-softserv/palni-palci/issues/951

**Comment by ShanaLMoore** [comment]
review odds and ends and october sprints for work we've done
