### ISSUE TITLE
Embed codes for media (see Atla instance)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#911]
## Summary
relevant tickets
- https://github.com/scientist-softserv/atla-hyku/issues/9

Pals would like to have the ability to embed YouTube videos onto a work show page, and they would like it to be implemented like Atla. 

The tagged PRs are:

- https://github.com/scientist-softserv/atla-hyku/pull/34
- https://github.com/scientist-softserv/atla-hyku/pull/46

## Task Breakdown

- [x] - [Implement video embed for Generic Works](https://github.com/scientist-softserv/palni-palci/pull/922)
- [x] - Implement video embed for other work types
  - [x] [CDL](https://github.com/scientist-softserv/palni-palci/pull/927)
  - [x] [Image](https://github.com/scientist-softserv/palni-palci/pull/928/files#diff-cb716bffdfff686cdbc6e5a7ebec30e8638f516a6aa4b512c381447570d7ba3c)
  - [x] [OER](https://github.com/scientist-softserv/palni-palci/pull/931) 
  - [x] [ETD](https://github.com/scientist-softserv/palni-palci/pull/929) 
- [x] - [Run translations](https://github.com/scientist-softserv/palni-palci/pull/926)
- [x] - [Add embedded video to other theme's show pages](https://github.com/scientist-softserv/palni-palci/pull/930)
- [x] when a user submits an invalid url, an error message should get thrown
  - [x] [The error message should support the various locales 
](https://github.com/scientist-softserv/palni-palci/pull/931)
## Acceptance Criteria
- [ ] As a user, I can add a link to a youtube video I would like to embed on the edit work form
- [ ] - [ ] As a user, I can add a link to a vimeo video I would like to embed on the edit work form
- [ ] As a user, i can add a column to bulkrax csv import that allows me to import a embedded video url (youtube and/or vimeo) that will be used in an iframe.
- [ ] As a user, I can visit that work's work-show page to see & play the embedded videos iframe
- [ ] Client is sent the correct info for what column to add to bulkrax csvs.
- [ ] Atla PRs that are related to this are added to Pals
- [ ] all work types are able to embed videos
- [ ] all themes show the embedded video
- [ ] embed links must be valid. A user cannot submit the form if not.

### BULKRAX

Import a sample CSV, but add a column called video_embed. The values will be the embed links from youtube and/or vimeo. 
After the jobs finish processing, navigate to the works' show pages to confirm the videos are there and playable. 

### OTHER

Either create works from scratch, and/or edit previously imported works. Add or change the video_embed field. 

### THEMES

After having a hand full of created works with video embeds, change the tenant's show theme.

**Comment by jillpe** [comment]
Can you give us more details here? Screenshots/videos are also welcome :)

**Comment by aahurford** [comment]
I reached out to Christy K at Atla for more info

**Comment by aahurford** [comment]
They do not have a live example, but here is a ticket that refers to the work: https://github.com/scientist-softserv/atla-hyku/pull/34

**Comment by kirkkwang** [comment]
# QA status ✅
Looks good to me, all works are showing up with the video player, tested with youtube and vimeo

**Comment by ndroark** [comment]
Would it be difficult to move the Video Embed to the Additional Fields section instead of the top section on the work upload form?

**Comment by ShanaLMoore** [comment]
sure, fix coming soon!

**Comment by ShanaLMoore** [comment]
Video embed is no longer above the additional fields: 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/69ad1f77-062d-4674-9f79-529a54312ab2)
